spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro_test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456

  redis:
    # redis默认情况下有16个分片，这里配置具体使用的分片，默认为0
    database: 0
    host: 127.0.0.1
    port: 6379
#    password: Chen1997
    lettuce:
      pool:
        # 连接池最大连接数(使用负数表示没有限制),默认8
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml # mapper映射
  global-config:
    db-config:
      logic-delete-field: deleteState  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #SQl日志

shiro:
  # session失效时间 毫秒
  globalSessionTimeOut: 86400000
  # 密码重试次数
  retryLimit: 5
  # 密码错误超出限制后，锁定时长 分钟
  userLockTime: 10